### PR TITLE
add device tree entry for ortus tech com43h4n10

### PR DESCRIPTION
**Pull request by braddr**
Initial mostly working version of the device tree config file for the ortustech com43h4n10 lcd panel.

Issues:
1) the initial varscite splash image top and bottom are slightly cropped
2) the porches might not be optimal
3) no touch screen configs in this pull

### CODE REVIEW

**Comment by ghost** [comment]
img_0312

[kernel_boot_log_for_brad.txt](https://github.com/SciAps/DART-SD410-kernel/files/2654050/kernel_boot_log_for_brad.txt)
[kernel_vanilla_boot_log_for_brad.txt](https://github.com/SciAps/DART-SD410-kernel/files/2654051/kernel_vanilla_boot_log_for_brad.txt)

**Comment by ghost** [comment]
@braddr I've attached both the vanilla kernel boot log and the boot log we see when using the kernel from your branch.

I've also uploaded a video of the blinking we are seeing here:
https://s3-us-west-2.amazonaws.com/sciaps-videos/IMG_0313.MOV

**Comment by braddr** [comment]
@sgowen Can this be pulled now based on our email thread and you  having it working on your hardware now too?  My touchscreen pull is currently built on top of this though I can separate the two if needed.

**Comment by ghost** [comment]
You can put all your work on this PR, we don't have to create another one.

**Comment by braddr** [comment]
Ok.. done.

**Pull request merged**
